FROM ruby:slim

LABEL Name={{ serviceName }} Version={{ version }}

{{#each ports}}
EXPOSE {{ . }}
{{/each}}

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

WORKDIR /app
COPY . /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

CMD ["ruby", "{{ serviceName }}.rb"]
