name: Info Needed Closer
on:
  schedule:
    - cron: 30 5 * * * # 10:30pm PT
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  main:
    uses: microsoft/vscode-azuretools/.github/workflows/info-needed-closer.yml@main
