name: Locker
on:
  schedule:
    - cron: 0 5 * * * # 10:00pm PT
  workflow_dispatch:

permissions:
  issues: write

jobs:
  main:
    uses: microsoft/vscode-azuretools/.github/workflows/locker.yml@main
